---
title: "Fesability"
author: "Pierce Edmiston"
output:
  html_document:
    theme: flatly
---

```{r config, echo = FALSE, message = FALSE}
library(knitr)

opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE
)

library(dplyr)
library(pander)
```

# Pilot

```{r, results = 'asis'}
subjs_per_dataset <- 4

data_frame(
  problem = c("adaptive", "insight"),
  `datasets (starting)` = c(8, 15),
  participants = `datasets (starting)` * subjs_per_dataset,
  `datasets (final)` = c(4, 10),
  `per participant ($)` = c(10, 5),
  `total cost ($)` = participants * `per participant ($)`
) %>%
  bind_rows(data_frame(`total cost ($)` = sum(.$`total cost ($)`))) %>%
  pandoc.table(justify = "left", split.tables = Inf, missing = "")
```

# Team structures

```{r, results = 'asis'}
team_size <- 4
teams_per_structure <- 20
cost_per_participant <- 20

total_participants <- team_size * teams_per_structure
total_cost <- total_participants * cost_per_participant

list(
  `team structures` = c("diachronic", "synchronic"),
  `team size` = team_size,
  `teams per structure` = teams_per_structure,
  `total participants` = total_participants,
  `per participant ($)` = cost_per_participant,
  `total cost ($)` = total_cost
) %>% pandoc.table(split.table = Inf)
```
