---
title: "Bots"
author: "Pierce Edmiston"
output:
  html_document:
    theme: flatly
---

```{r config, echo = FALSE, message = FALSE}
library(knitr)
library(tidyverse)
library(jsonlite)
library(evoteams)
library(crotchet)

opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  fig.path = "figs/",
  fig.width = 3,
  fig.height = 3,
  cache.path = ".cache/"
)

base_theme <- theme_minimal() +
  theme(legend.position = "none")

strategy_colors <- RColorBrewer::brewer.pal(3, "Set2")[c(1, 3)]
scale_color_strategy <- scale_color_manual(values = strategy_colors)
scale_fill_strategy <- scale_fill_manual(values = strategy_colors)


```

# Team structures

```{r team-structures, fig.width = 3}
diagram_graphviz("team-structures", "evoteams")
```

# Results

## Replication

```{r}
data("bots_replication")

ggplot(bots_replication) +
  aes(round, inventory_size, color = strategy) +
  geom_line(stat = "summary", fun.y = "mean") +
  scale_color_strategy +
  base_theme

bots_replication_final <- bots_replication %>%
  group_by(strategy, sim_id) %>%
  filter(round == max(round))

ggplot(bots_replication_final) +
  aes(strategy, inventory_size) +
  geom_bar(aes(fill = strategy), stat = "summary", fun.y = "mean",
           alpha = 0.6) +
  geom_point(aes(color = strategy), position = position_jitter(0.3),
             shape = 1) +
  scale_color_strategy +
  scale_fill_strategy +
  base_theme
```

# Modeling results

```{r}
data("bots_main")

ggplot(bots_main) +
  aes(round, inventory_size, color = strategy) +
  geom_line(stat = "summary", fun.y = "mean") +
  scale_color_strategy +
  base_theme

bots_main_final <- bots_main %>%
  group_by(strategy, sim_id) %>%
  filter(round == max(round))

ggplot(bots_main) +
  aes(strategy, inventory_size) +
  geom_bar(aes(fill = strategy), stat = "summary", fun.y = "mean",
           alpha = 0.6) +
  scale_color_strategy +
  scale_fill_strategy +
  base_theme
```