devtools::load_all("~/Research/DiachronicTeams/data")
# ---- setup
library(tidyverse)
library(magrittr)
library(broom)
library(lme4)
library(AICcmodavg)
library(gridExtra)
library(crotchet)
library(totems)
t_ <- load_totems_theme()
