---
title: "Comparing different performance metrics"
author: "Pierce Edmiston"
output:
  html_document:
    theme: flatly
---

```{r config, include=FALSE}
library(knitr)

opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  results = "hide",
  fig.width = 4,
  fig.height = 4,
  cache = TRUE
)

read_chunk("../R/setup.R")
read_chunk("../R/performance.R")
```

```{r setup}
```

```{r performance}
```

```{r}
data("PlayerPerformance")

PerformanceByGeneration <- PlayerPerformance %>%
  filter(
    Exp == "50LaborMinutes",
    Strategy != "Synchronic",
    SessionDuration == 25,
    TeamStatus == "V",
    SessionStatus == "V"
  )

ggplot(PerformanceByGeneration) +
  aes(Generation, NumInnovations) +
  geom_bar(stat = "summary", fun.y = "mean", alpha = 0.4) +
  geom_line(aes(group = TeamID), alpha = 0.4) +
  geom_line(stat = "summary", fun.y = "mean", size = 2) +
  facet_wrap("Strategy")

ggplot(PerformanceByGeneration) +
  aes(Generation, NumGuesses) +
  geom_bar(stat = "summary", fun.y = "mean", alpha = 0.4) +
  geom_line(aes(group = TeamID), alpha = 0.4) +
  geom_line(stat = "summary", fun.y = "mean", size = 2) +
  facet_wrap("Strategy")

ggplot(PerformanceByGeneration) +
  aes(Generation, NumUniqueGuesses) +
  geom_bar(stat = "summary", fun.y = "mean", alpha = 0.4) +
  geom_line(aes(group = TeamID), alpha = 0.4) +
  geom_line(stat = "summary", fun.y = "mean", size = 2) +
  facet_wrap("Strategy") +
  ggtitle("")
```