---
title: "Survey responses"
output:
  html_document:
    theme: flatly
---
```{r config, include=FALSE}
library(knitr)
library(printr)
read_chunk("../R/setup.R")
```

```{r setup, include=FALSE}
```

```{r survey-questions}
data("SurveyQuestions")
SurveyQuestions
```

## Correlation among numeric questions

```{r correlation}
data("Survey")

SurveyNumeric <- Survey %>%
  filter(QuestionTag %in% c("familiar", "enjoyable", "difficulty")) %>%
  mutate(Response = as.numeric(Response)) %>%
  select(ID_Participant, QuestionTag, Response) %>%
  spread(QuestionTag, Response) %>%
  mutate(jitter = runif(n(), -1, 1))

survey_plot <- ggplot(SurveyNumeric) +
  geom_point(position = "jitter") +
  geom_smooth(method = "lm", se = FALSE)
```

```{r cor-table}
cor(SurveyNumeric[, 2:4], use = "pairwise.complete.obs")
```

### People who are familiar with the game find it more enjoyable

```{r familiar-and-enjoyable}
survey_plot +
  aes(familiar, enjoyable)
```

### People who find the game more difficult find it less enjoyable

```{r difficult-and-enjoyable}
survey_plot +
  aes(difficulty, enjoyable)
```

### People who are more familiar with the game find it less difficult

```{r familiar-and-difficult}
survey_plot +
  aes(familiar, difficulty)
```
