---
title: "Bots"
author: "Pierce Edmiston"
output:
  html_document:
    theme: flatly
---

```{r config, include = FALSE}
library(knitr)
library(tidyverse)
library(magrittr)
library(grid)
library(gridExtra)
library(jsonlite)
library(totems)
library(crotchet)

opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  results = "hide",
  fig.path = "figs/",
  fig.width = 6,
  fig.height = 3,
  cache.path = ".cache.modeling/"
)
```

```{r theme, include = FALSE}
base_theme <- theme_minimal()

strategy_colors <- RColorBrewer::brewer.pal(3, "Set2")[c(1, 3)]
scale_color_strategy <- scale_color_manual(values = strategy_colors)
scale_fill_strategy <- scale_fill_manual(values = strategy_colors)

# inventory
min_inventory_size <- 6
max_inventory_size <- 33
scale_y_inventory_size <- scale_y_continuous("size of inventory",
                                             breaks = c(min_inventory_size, max_inventory_size,
                                                        seq(10, 30, by = 5)))
coord_inventory_lim <- c(min_inventory_size, max_inventory_size)
```

```{r templates, include = FALSE}
gg_timeline <- ggplot() +
  aes(round, inventory_size, color = strategy) +
  geom_line(stat = "summary", fun.y = "mean") +
  scale_color_strategy +
  scale_y_inventory_size +
  coord_cartesian(ylim = coord_inventory_lim) +
  base_theme +
  theme(legend.position = "top")

gg_final <- ggplot() +
  aes(strategy, inventory_size) +
  geom_bar(aes(fill = strategy), stat = "summary", fun.y = "mean",
           alpha = 0.6) +
  geom_point(aes(color = strategy), position = position_jitter(0.3),
             shape = 1) +
  scale_y_inventory_size +
  coord_cartesian(ylim = coord_inventory_lim) +
  scale_color_strategy +
  scale_fill_strategy +
  base_theme +
  theme(legend.position = "none")
```

```{r helpers, include = FALSE}
sim_vars <- c("strategy", "n_guesses", "n_players", "seed", "player_memory", "team_memory")

filter_final_round <- . %>%
  group_by_(.dots = sim_vars) %>%
  filter(round == max(round)) %>%
  ungroup()

recode_team_memory <- function(frame) {
  team_memory_levels <- c("no team memory", "yes team memory")
  team_memory_map <- data_frame(
    team_memory = c(0, 1),
    team_memory_label = factor(team_memory_levels, levels = rev(team_memory_levels))
  )
  left_join(frame, team_memory_map)
}

recode_player_memory <- function(frame) {
  player_memory_levels <- c("no player memory", "yes player memory")
  player_memory_map <- data_frame(
    player_memory = c(0, 1),
    player_memory_label = factor(player_memory_levels, levels = player_memory_levels)
  )
  left_join(frame, player_memory_map)
}

recode_memory <- . %>%
  recode_team_memory() %>%
  recode_player_memory() 
```

# Team structures

```{r team-structures, fig.width = 2.5}
diagram_graphviz("team-structures", "totems")
```

# Experiments

## Replication

```{r}
data("simulations_replication")
grid.arrange(
  read_graphviz("calendar-hours", "totems"),
  gg_timeline %+% simulations_replication,
  gg_final %+% filter_final_round(simulations_replication),
  nrow = 1
)
```

## Strategy

```{r}
data("simulations_strategy")
gg_timeline %+% simulations_strategy
gg_final %+% filter_final_round(simulations_strategy)
```

## Team size

```{r}
data("simulations_players")
gg_final %+% filter_final_round(simulations_players)
(gg_timeline %+% filter_final_round(simulations_players)) +
  aes(n_players, inventory_size, color = strategy) +
  scale_x_continuous("team size", breaks = unique(simulations_players$n_players)) +
  theme(panel.grid.minor.x = element_blank())
```

## Number of guesses

```{r}
data("simulations_guesses")
gg_timeline %+% filter_final_round(simulations_guesses) +
  aes(n_guesses)
```

## Player and team memory

```{r, fig.height=6}
data("simulations_memory")

simulations_memory %<>%
  recode_memory()

gg_timeline %+% simulations_memory +
  facet_grid(team_memory_label ~ player_memory_label)

gg_final %+% filter_final_round(simulations_memory) +
  facet_grid(team_memory_label ~ player_memory_label)
```