---
title: "The impact of inheritance on problem solving"
author: "Pierce Edmiston"
output:
  html_document:
    theme: flatly
    css: theme/style.css
    toc: true
    toc_depth: 2
    toc_float: true
---

```{r config, include = FALSE}
library(knitr)
library(printr)
library(magrittr)
library(crotchet)

opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  results = "hide",
  fig.width = 4,
  fig.height = 4,
  cache = TRUE
)

list.files("R", "*.R", full.names = TRUE) %>% sapply(read_chunk)
```

```{r setup}
```

# 50 Labor Minutes

## Performance

### Inventory size

```{r performance-50}
```

### Likelihood of creating a totem

```{r likelihood-50}
```

### Performance by session duration

```{r session-duration}
```

### Performance over multiple sessions

```{r performance-by-generation-50}
```

## Guesses

### Number of attempts

```{r guesses-50}
```

```{r unique-guesses-50}
```

### Number of attempts and performance

```{r guesses-50-performance}
```

```{r unique-guesses-50-performance}
```

### Number of attempts by generation

```{r guesses-50-generation}
```

### Number of attempts by session duration

```{r guesses-50-session-duration}
```

# 100 Labor Minutes

## Performance

```{r performance-100}
```

```{r performance-by-generation-100}
```

## Likelihood

```{r likelihood-100}
```

## Attempts

```{r player-guesses-all}
```
